// Generated by gencpp from file epos_tutorial/realVel.msg
// DO NOT EDIT!


#ifndef EPOS_TUTORIAL_MESSAGE_REALVEL_H
#define EPOS_TUTORIAL_MESSAGE_REALVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace epos_tutorial
{
template <class ContainerAllocator>
struct realVel_
{
  typedef realVel_<ContainerAllocator> Type;

  realVel_()
    : realVel()  {
      realVel.assign(0);
  }
  realVel_(const ContainerAllocator& _alloc)
    : realVel()  {
  (void)_alloc;
      realVel.assign(0);
  }



   typedef boost::array<int32_t, 4>  _realVel_type;
  _realVel_type realVel;





  typedef boost::shared_ptr< ::epos_tutorial::realVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epos_tutorial::realVel_<ContainerAllocator> const> ConstPtr;

}; // struct realVel_

typedef ::epos_tutorial::realVel_<std::allocator<void> > realVel;

typedef boost::shared_ptr< ::epos_tutorial::realVel > realVelPtr;
typedef boost::shared_ptr< ::epos_tutorial::realVel const> realVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epos_tutorial::realVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epos_tutorial::realVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace epos_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'epos_tutorial': ['/home/jeon/test_ws/src/epos_tutorial/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::epos_tutorial::realVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epos_tutorial::realVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos_tutorial::realVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos_tutorial::realVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos_tutorial::realVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos_tutorial::realVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epos_tutorial::realVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "260e0cec7f1efbe2a3d504ab70436964";
  }

  static const char* value(const ::epos_tutorial::realVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x260e0cec7f1efbe2ULL;
  static const uint64_t static_value2 = 0xa3d504ab70436964ULL;
};

template<class ContainerAllocator>
struct DataType< ::epos_tutorial::realVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epos_tutorial/realVel";
  }

  static const char* value(const ::epos_tutorial::realVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epos_tutorial::realVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[4] realVel\n\
";
  }

  static const char* value(const ::epos_tutorial::realVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epos_tutorial::realVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.realVel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct realVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epos_tutorial::realVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epos_tutorial::realVel_<ContainerAllocator>& v)
  {
    s << indent << "realVel[]" << std::endl;
    for (size_t i = 0; i < v.realVel.size(); ++i)
    {
      s << indent << "  realVel[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.realVel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPOS_TUTORIAL_MESSAGE_REALVEL_H
