// Generated by gencpp from file epos_tutorial/VelCommand.msg
// DO NOT EDIT!


#ifndef EPOS_TUTORIAL_MESSAGE_VELCOMMAND_H
#define EPOS_TUTORIAL_MESSAGE_VELCOMMAND_H

#include <ros/service_traits.h>


#include <epos_tutorial/VelCommandRequest.h>
#include <epos_tutorial/VelCommandResponse.h>


namespace epos_tutorial
{

struct VelCommand
{

typedef VelCommandRequest Request;
typedef VelCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VelCommand
} // namespace epos_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::epos_tutorial::VelCommand > {
  static const char* value()
  {
    return "5a55dd5615c5c9508a58c372e3bab322";
  }

  static const char* value(const ::epos_tutorial::VelCommand&) { return value(); }
};

template<>
struct DataType< ::epos_tutorial::VelCommand > {
  static const char* value()
  {
    return "epos_tutorial/VelCommand";
  }

  static const char* value(const ::epos_tutorial::VelCommand&) { return value(); }
};


// service_traits::MD5Sum< ::epos_tutorial::VelCommandRequest> should match 
// service_traits::MD5Sum< ::epos_tutorial::VelCommand > 
template<>
struct MD5Sum< ::epos_tutorial::VelCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::epos_tutorial::VelCommand >::value();
  }
  static const char* value(const ::epos_tutorial::VelCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::epos_tutorial::VelCommandRequest> should match 
// service_traits::DataType< ::epos_tutorial::VelCommand > 
template<>
struct DataType< ::epos_tutorial::VelCommandRequest>
{
  static const char* value()
  {
    return DataType< ::epos_tutorial::VelCommand >::value();
  }
  static const char* value(const ::epos_tutorial::VelCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::epos_tutorial::VelCommandResponse> should match 
// service_traits::MD5Sum< ::epos_tutorial::VelCommand > 
template<>
struct MD5Sum< ::epos_tutorial::VelCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::epos_tutorial::VelCommand >::value();
  }
  static const char* value(const ::epos_tutorial::VelCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::epos_tutorial::VelCommandResponse> should match 
// service_traits::DataType< ::epos_tutorial::VelCommand > 
template<>
struct DataType< ::epos_tutorial::VelCommandResponse>
{
  static const char* value()
  {
    return DataType< ::epos_tutorial::VelCommand >::value();
  }
  static const char* value(const ::epos_tutorial::VelCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EPOS_TUTORIAL_MESSAGE_VELCOMMAND_H
