// Generated by gencpp from file epos_tutorial/VelCommandResponse.msg
// DO NOT EDIT!


#ifndef EPOS_TUTORIAL_MESSAGE_VELCOMMANDRESPONSE_H
#define EPOS_TUTORIAL_MESSAGE_VELCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace epos_tutorial
{
template <class ContainerAllocator>
struct VelCommandResponse_
{
  typedef VelCommandResponse_<ContainerAllocator> Type;

  VelCommandResponse_()
    : setVel1(0)
    , setVel2(0)
    , setVel3(0)
    , setVel4(0)  {
    }
  VelCommandResponse_(const ContainerAllocator& _alloc)
    : setVel1(0)
    , setVel2(0)
    , setVel3(0)
    , setVel4(0)  {
  (void)_alloc;
    }



   typedef int64_t _setVel1_type;
  _setVel1_type setVel1;

   typedef int64_t _setVel2_type;
  _setVel2_type setVel2;

   typedef int64_t _setVel3_type;
  _setVel3_type setVel3;

   typedef int64_t _setVel4_type;
  _setVel4_type setVel4;





  typedef boost::shared_ptr< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VelCommandResponse_

typedef ::epos_tutorial::VelCommandResponse_<std::allocator<void> > VelCommandResponse;

typedef boost::shared_ptr< ::epos_tutorial::VelCommandResponse > VelCommandResponsePtr;
typedef boost::shared_ptr< ::epos_tutorial::VelCommandResponse const> VelCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epos_tutorial::VelCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace epos_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'epos_tutorial': ['/home/jeon/test_ws/src/epos_tutorial/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62dd1bf6da19d859801ad5640e8feee2";
  }

  static const char* value(const ::epos_tutorial::VelCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62dd1bf6da19d859ULL;
  static const uint64_t static_value2 = 0x801ad5640e8feee2ULL;
};

template<class ContainerAllocator>
struct DataType< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epos_tutorial/VelCommandResponse";
  }

  static const char* value(const ::epos_tutorial::VelCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 setVel1\n\
int64 setVel2\n\
int64 setVel3\n\
int64 setVel4\n\
\n\
";
  }

  static const char* value(const ::epos_tutorial::VelCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setVel1);
      stream.next(m.setVel2);
      stream.next(m.setVel3);
      stream.next(m.setVel4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epos_tutorial::VelCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epos_tutorial::VelCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "setVel1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.setVel1);
    s << indent << "setVel2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.setVel2);
    s << indent << "setVel3: ";
    Printer<int64_t>::stream(s, indent + "  ", v.setVel3);
    s << indent << "setVel4: ";
    Printer<int64_t>::stream(s, indent + "  ", v.setVel4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPOS_TUTORIAL_MESSAGE_VELCOMMANDRESPONSE_H
